### PR TITLE
parse and colorize also directory structure

### PR DESCRIPTION
**Pull request by stettberger**
There was an error in the default regex. And I also parse the directory structure properly.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks for your contribution, I have added some comment in the code.
Please have a look and fix before merging.

**Comment by stettberger** [comment]
So, i've updated the issues you have (rightfully) adressed

**Comment by thierryvolpiatto** [comment]
also `prefix` is no more used in `helm-firefox-bookmarks-to-alist` you can remove it.

**Comment by thierryvolpiatto** [comment]
I will have a look at indentation ASAP and correct if necessary.

Thanks!

**Pull request merged**
